---
release_tags: &release_tags
  tags:
    only: /^v\d+(\.\d+){2}(-.*)?$/

# "Include" for unit tests definition.
unit_tests: &unit_tests
  steps:
    - checkout
    - run: npm install
    - run: npm test

version: 2.0
workflows:
  version: 2
  tests:
    jobs:
      - node10:
          filters: *release_tags
      - node12:
          filters: *release_tags
      - node13:
          filters: *release_tags
      - lint:
          filters: *release_tags
      - codecov:
          filters: *release_tags
      - publish_npm:
          requires:
            - node10
            - node12
            - node13
            - codecov
            - lint
          filters:
            branches:
              ignore: /.*/
            <<: *release_tags

jobs:
  node10:
    docker:
      - image: node:10
        user: node
    <<: *unit_tests
  node12:
    docker:
      - image: node:12
        user: node
    <<: *unit_tests
  node13:
    docker:
      - image: node:13
        user: node
    <<: *unit_tests
  codecov:
    docker:
      - image: node:13
        user: node
    steps:
      - checkout
      - run: npm install
      - run: npm test
      - run: npm run codecov
  lint:
    docker:
      - image: node:13
        user: node
    steps:
      - checkout
      - run: npm install
      - run: npm run check

  publish_npm:
    docker:
      - image: node:13
        user: node
    steps:
      - checkout
      - run: npm ci
      - run: npm run compile
      - run: echo "//wombat-dressing-room.appspot.com/:_authToken=${NPM_TOKEN}" > ~/.npmrc
      - run: npm publish --registry https://wombat-dressing-room.appspot.com/
